@TripNow.Api_HostAddress = http://localhost:5199

POST {{TripNow.Api_HostAddress}}/reservations/
Accept: application/json
{
  "CustomerEmail": "test@test.com",
  "TripCountry" : "Cuba",
  "Amount": 100.00
}
###
